### ISSUE TITLE
Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by Alonew0lfxx** [mrousavy/react-native-mmkv#332]
While I developing my app (for ex. building the screens) for a while app really works without any problems. But after React-Native starts giving errors like this and stops synchronizing. 

This is the log output of app after a screen refresh:
```
 BUNDLE  ./index.js 

 ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling startHeadlessTask). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling startHeadlessTask). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling startHeadlessTask). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
      
```

package.json:
```
{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-clipboard/clipboard": "^1.9.0",
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@reduxjs/toolkit": "^1.7.2",
    "@types/chance": "^1.1.3",
    "chance": "^1.1.8",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.5",
    "react-native-mmkv": "^2.0.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.9.0",
    "react-native-share": "^7.3.5",
    "react-native-svg": "^12.1.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-url-polyfill": "^1.3.0",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

react-native info:
```
ws PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\steam\WebstormProjects\MyProject> npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
    Memory: 5.81 GB / 15.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-22 | Intel x86 Atom, android-23 | Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Google Play Intel x8
6 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    Visual Studio: Not Found
  Languages:
    Java: 16.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
PS C:\Users\steam\WebstormProjects\MyProject>
```

**Comment by azc-lionx** [comment]
If you are getting this error just in Jest, you can use:
```typescript
jest.mock('react-native-mmkv', () => ({
  MMKV: function () {
    const store: Record<string, string> = {};
    return {
      set: (key: string, value: string): void => {
        store[key] = value;
      },
      getString: (key: string): string | null => store[key] || null,
      contains: (key: string): boolean => Object.prototype.hasOwnProperty.call(store, key),
    };
  },
}));
```

**Comment by azizmobarak** [comment]
I imported MMKVStorage from the library to use the API from the space on `RN 0.69.5` and `RN-MMKV 0.7.0 `
it says `the MMKVStorage space not found` but when I back `0.6.x `it works but there is a bug for new arch as mentioned before on an issue and that is fixed on `0.7.0` where I got that issue (I didn't face it before)

**Comment by antoniel** [comment]
Even using @mrousavy implementation I was still getting jest issues while running MMKV on test env, so I built an even more complete test function based on the actual implementation of MMKV,

```typescript 
// __mocks__/react-native-mmkv.js
jest.mock('react-native-mmkv', () => {
  const actualMMKV = jest.requireActual('react-native-mmkv')
  const React = jest.requireActual('react')
  class MMKV {
    storage
    onValueChangedListeners
    constructor() {
      this.storage = new Map()
      this.onValueChangedListeners = []
    }

    set(key, value) {
      this.storage.set(key, value)
      this.onValuesChanged([key])
    }

    getString(key) {
      const result = this.storage.get(key)
      if (typeof result === 'string') return result
      else return undefined
    }

    getNumber(key) {
      const result = this.storage.get(key)
      if (typeof result === 'number') return result
      else return undefined
    }

    getBoolean(key) {
      const result = this.storage.get(key)
      if (typeof result === 'boolean') return result
      else return undefined
    }

    contains(key) {
      return this.storage.has(key)
    }

    delete(key) {
      this.storage.delete(key)
      this.onValuesChanged([key])
    }

    getAllKeys() {
      return this.storage.keys()
    }

    clearAll() {
      return this.storage.clear()
    }

    recrypt() {
      console.warn('Encryption is not supported in mocked MMKV instances!')
    }

    onValuesChanged(keys) {
      if (this.onValueChangedListeners.length === 0) return

      for (const key of keys) {
        for (const listener of this.onValueChangedListeners) {
          listener(key)
        }
      }
    }
    _chad
    addOnValueChangedListener(onValueChanged) {
      this.onValueChangedListeners.push(onValueChanged)

      return {
        remove: () => {
          const index = this.onValueChangedListeners.indexOf(onValueChanged)
          if (index !== -1) {
            this.onValueChangedListeners.splice(index, 1)
          }
        },
      }
    }
  }
  const createMMKVHook = (getter) => {
    return (key, instance) => {
      const mmkv = instance ?? getDefaultInstance()
      const [value, setValue] = React.useState(() => getter(mmkv, key))
      const valueRef = React.useRef(value)
      valueRef.current = value

      // update value by user set
      const set = React.useCallback(
        (v) => {
          const newValue = typeof v === 'function' ? v(valueRef.current) : v
          switch (typeof newValue) {
            case 'number':
            case 'string':
            case 'boolean':
              mmkv.set(key, newValue)
              break
            case 'undefined':
              mmkv.delete(key)
              break
            default:
              throw new Error(`MMKV: Type ${typeof newValue} is not supported!`)
          }
        },
        [key, mmkv]
      )

      // update value if key changes
      const keyRef = React.useRef(key)
      React.useEffect(() => {
        if (key !== keyRef.current) {
          setValue(getter(mmkv, key))
          keyRef.current = key
        }
      }, [key, mmkv])

      // update value if it changes somewhere else (second hook, same key)
      React.useEffect(() => {
        const listener = mmkv.addOnValueChangedListener((changedKey) => {
          if (changedKey === key) {
            setValue(getter(mmkv, key))
          }
        })
        return () => listener.remove()
      }, [key, mmkv])

      return [value, set]
    }
  }
  const getDefaultInstance = () => {
    return new MMKV()
  }
  const useMMKVString = createMMKVHook((instance, key) => instance.getString(key))
  // TODO: mock useMMKVObject correctly
  const useMMKVObject = () => [0, () => null]
  const defaultInstance = new MMKV()

  return {
    MMKV,
    getDefaultInstance: () => defaultInstance,
    createMMKVHook: createMMKVHook,
    useMMKVString,
    useMMKVObject,
  }
})

```

**Comment by jtvargas** [comment]
> Yeah that's because react-native-mmkv does not have automatic mocking available (yet).
> 
> btw Here's a more complete mock that supports all functions from MMKV, not just `set` and `getString`:
> 
> jest.mock('react-native-mmkv', () => ({
>   MMKV: function () {
> 
>     const storage = new Map<string, string | boolean | number>()
> 
>     return {
>         set: (key: string, value: string): void => {
>             storage.set(key, value)
>         },
>         getString: (key: string): string | undefined => {
>             const result = storage.get(key)
>             if (typeof result === "string") return result
>             else return undefined
>         },
>         getNumber: (key: string): number | undefined => {
>             const result = storage.get(key)
>             if (typeof result === "number") return result
>             else return undefined
>         },
>         getBoolean: (key: string): boolean | undefined => {
>             const result = storage.get(key)
>             if (typeof result === "boolean") return result
>             else return undefined
>         },
>         contains: (key: string): boolean => storage.has(key),
>         delete: (key: string) => {
>             storage.delete(key)
>         },
>         getAllKeys: () => storage.keys(),
>         clearAll: () => storage.clear(),
>         recrypt: () => {
>             console.warn('Encryption is not supported in mocked MMKV instances!')
>         },
>         addOnValueChangedListener: () => {
>             console.warn('Value-changed listeners are not supported in mocked MMKV instances!')
>         }
>     };
>   }
> }));

I was having issues in my Jest test after updating from v2 to v4, so I needed to add these mock updates to get all my tests passing  and since the mock you provided doesn't include some of the latest functions. Here is an updated version that worked for me:

```
jest.mock('react-native-mmkv', () => ({
  createMMKV: function () {

    const storage = new Map<string, string | boolean | number>()

    return {
        set: (key: string, value: string): void => {
            storage.set(key, value)
        },
        getString: (key: string): string | undefined => {
            const result = storage.get(key)
            if (typeof result === "string") return result
            else return undefined
        },
        getNumber: (key: string): number | undefined => {
            const result = storage.get(key)
            if (typeof result === "number") return result
            else return undefined
        },
        getBoolean: (key: string): boolean | undefined => {
            const result = storage.get(key)
            if (typeof result === "boolean") return result
            else return undefined
        },
        contains: (key: string): boolean => storage.has(key),
        remove: (key: string) => {
            storage.delete(key)
        },
        getAllKeys: () => storage.keys(),
        clearAll: () => storage.clear(),
        recrypt: () => {
            console.warn('Encryption is not supported in mocked MMKV instances!')
        },
        addOnValueChangedListener: () => {
            console.warn('Value-changed listeners are not supported in mocked MMKV instances!')
        }
    };
  }
}));
```

Maybe it would be good to add in the README.md 👀

**Comment by mrousavy** [comment]
Can you add a PR to add this to react-native-mmkv ? I believe we have a mock here in the repo
