### ISSUE TITLE
Build Fails on React Native 0.71.0 when fabric enabled

### ISSUE THREAD

**Issue by devoren** [mrousavy/react-native-mmkv#501]
If fabric disabled it works fine after [#497](https://github.com/mrousavy/react-native-mmkv/issues/497) but if i enable fabric [this](https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1384902642) error appears again
<img width="707" alt="image" src="https://user-images.githubusercontent.com/99968085/213135968-43a7f533-1f8a-49f7-a492-395242cd9af1.png">

If i remove MMKV it works in fabric without error

**Comment by mrousavy** [comment]
Does it also not work with RN MMKV 2.6.1?

**Comment by devoren** [comment]
@mrousavy yes

**Comment by ievolution** [comment]
Same behavior after `clean` project during the build with fabric enabled.

**Comment by devoren** [comment]
@ievolution Did it work before clean with fabric?

**Comment by ievolution** [comment]
> @ievolution Did it work before clean with fabric?

Nope. The graddle sync is successful, but the build fails with the same error you have

**Comment by mrousavy** [comment]
I'm sorry, I can't reproduce this error.

**Comment by devoren** [comment]
@mrousavy Okay then i use it without fabric, thanks for the quick reply

**Comment by mrousavy** [comment]
@Titozzz can you reproduce this?

**Comment by Titozzz** [comment]
This is usually local cache issue

**Comment by sssajjad007** [comment]
> I'm sorry, I can't reproduce this error.

I create a simple repo, I have same problem with android build.
hope you can help.
https://github.com/sssajjad007/vendor

**Comment by devoren** [comment]
@sssajjad007 do you have the same error with fabric?

**Comment by sssajjad007** [comment]
> @sssajjad007 do you have the same error with fabric?

Yes

**Comment by devoren** [comment]
> Yes

@sssajjad007 Please, Try it in RN 0.71.1 it might work, but I haven't tried it yet

**Comment by devoren** [comment]
> This is usually local cache issue

@Titozzz  i cleared home gradle caches and app caches + removed node modules but it didn't help. Is there any chance the libraries might conflict with each other? Conflict with RNGH? 
RNGH: ^2.9.0
react-native-mmkv: ^2.6.1
react-native: 0.71.1
Log after all cleans: 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/99968085/213872725-dd58992b-4482-48af-835d-c0b238285407.png">

**Comment by devoren** [comment]
> i created this repo on 71.1, but still have problem https://github.com/sssajjad007/vendor

@sssajjad007  me too

**Comment by 98rahul** [comment]
correct!
 facing same issue  for the latest version of RN-0.71.1 with mmkv  [same](https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1399898088)

**Comment by pyrokasper** [comment]
yo, accidentally saw this problem and decided to check. Everything works fine for me, I attach a screenshot. Therefore, gentlemen, this is your local problem, perhaps a conflict with other dependencies or a cache.

![изображение](https://user-images.githubusercontent.com/94339260/214203131-9f23c67c-98e4-486a-b7c6-33b0a3813e2c.png)

package.json:

```json
{
  "name": "fabric",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@shopify/flash-list": "^1.4.0",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-mmkv": "^2.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "reactotron-react-native": "^5.0.3",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by Yrsafam** [comment]
yo, accidentally saw this problem and decided to check. Everything works fine for me, I attach a screenshot. Therefore, gentlemen, this is your local problem, perhaps a conflict with other dependencies or a cache.

![изображение](https://user-images.githubusercontent.com/94339260/214203131-9f23c67c-98e4-486a-b7c6-33b0a3813e2c.png)

package.json:

```json
{
  "name": "fabric",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@shopify/flash-list": "^1.4.0",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-mmkv": "^2.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "reactotron-react-native": "^5.0.3",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by devoren** [comment]
@Yrsafam Wow cool! I think it conflicts with RNGH? can you use it with RNGH?

**Comment by 98rahul** [comment]
@Yrsafam , just saw you are using RN -0.71.1 with mmkv -"^2.6.1" , and your RN- app is running(correct!).
But, i'm getting [link](https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1399898088) with using the current version of RN.

**Comment by Yrsafam** [comment]
@devoren , yes, a similar error occurs when adding RNGH. In this case, it is difficult to say on whose side the problem is. Perhaps some class names really overlap and this should not be the case. Here you need to delve into the way to create a module based on the new react-native architecture. Unfortunately I don't have time for this right now

**Comment by Yrsafam** [comment]
@98rahul , at the moment, the current version of react-native is [0.71.1](https://github.com/facebook/react-native/releases/tag/v0.71.1). I suspect in your case it is easiest to upgrade to the latest version because perhaps the problem is in the area of responsibility of react-native, which has been fixed by the patch

**Comment by 98rahul** [comment]
@Yrsafam  using the latest version of RN-0.71.1 and running smoothly .
while on adding RN-mmkv -2.6.1 build fails [error](https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1399898088)

**Comment by Yrsafam** [comment]
@98rahul, There is too little input data. Is the project absolutely clean? Is there only one third-party dependency in the project in the form of react-native-mmkv? After experimenting with RNGH, after deleting the package, I could not restart the project until I cleared the cache through `gradlew clean` and deleted the `android/app/.cxx folder`

**Comment by 98rahul** [comment]
@Yrsafam  project  already built , moving with current version of RN-0.71.1,  from the official docs [0.71.1](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#removed) as asyncstorage had been removed.

greetings -:) 
issue been resolved .
just deleted the installed  ndk version mention in (android.build.gradle)  from the .....\AppData\Local\Android\Sdk\ndk\23.1.7779620 
and start the run command.
ndk will ready -->> complete-->> finished.

**Comment by dennisvk001** [comment]
Still facing this error (Error while merging dex archives) while compiling:
- RN: 0.71.1
- mmkv: 2.6.1
- RNGH: 2.9.0

Cleaning Gradle (even deleting .gradle folder) doesn't help.

Compiling on fresh RN 0.71.1 only with mmkv working fine.

**Comment by devoren** [comment]
@dennisvk001 Yes, it conflicts with RNGH

**Comment by dennisvk001** [comment]
After applying changes from #506 project compiled without any issues.

**Comment by devoren** [comment]
@dennisvk001 Yeah cool! Thanks for reminding me

**Comment by devoren** [comment]
After upgrading RN to [v0.71.2](https://github.com/facebook/react-native/releases/tag/v0.71.2) issue was resolved

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=iL-o8IJhwSQ&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=16
