### ISSUE TITLE
[ANDROID] Build error react-native-mmkv:configureCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by phungrs** [mrousavy/react-native-mmkv#563]
I got this error when building app in andoird

```
* What went wrong:
Execution failed for task ':react-native-mmkv:configureCMakeDebug[arm64-v8a]'.
> [CXX1428] exception while building Json A problem occurred starting process 'command '/Users/mjlt2/Library/Android/sdk/cmake/3.22.1/bin/cmake''
```

Env
-  "react-native": "0.72.3",
-  "react-native-mmkv": "^2.10.1"

Please help me.

![image](https://github.com/mrousavy/react-native-mmkv/assets/139065319/31502fd8-709e-4ca8-abf6-d89284ce807a)

**Comment by rodrigotbrun** [comment]
I fixed this issue by installing rosetta with:

```
softwareupdate --install-rosetta
```

I did a reset to my m1 macbook, and I haven't installed rosetta, but this fixed for me.

**Comment by gorkmbs** [comment]
Same issue on windows

**Comment by exploitJ** [comment]
0.72 version uses cmake 3.22.1 by default.
0.71 version builds without a problem.
project needs to upgrade its build system to cmake 3.22.1

**Comment by RagavendraM** [comment]
Is there any update on this?

**Comment by defolly** [comment]
@exploitJ , by the way,  how to upgrade the project cmake

**Comment by defolly** [comment]
@exploitJ , thanks.  change the ndkVersion from 24.0.8215888 to  25.2.9519653 , it work for me.

       if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            // ndkVersion = "24.0.8215888"
            ndkVersion = "25.2.9519653"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }

**Comment by flaming-streamz** [comment]
> I seem to have similar issue in 0.72. A problem occurred configuring project ':react-native-mmkv'.
> 
> > Could not create task ':react-native-mmkv:configureCMakeDebug[armeabi-v7a]'.
> > "react-native-mmkv": "2.10.2",
> > "react-native": "0.72.4",

@wezter96 did you find a solution for this ☝️

**Comment by LeoInCode** [comment]
Any updates? I have the same problem here, e nothing what I try resolve this issue.

**Comment by patlux** [comment]
Checkout if you have set `_JAVA_OPTIONS`

```sh
echo $_JAVA_OPTIONS
```

If so, unset it and try it again:

```sh
unset _JAVA_OPTIONS
yarn android
```

This fixed it for me. I don't know why. I set it because I had some troubles in the past with ipv6.

**Comment by rada** [comment]
Try following [these steps](https://dev.to/retyui/react-native-fix-android-build-error-cxx1428-exception-while-building-json-a-problem-occurred-starting-process-5e2c) This worked for me just by uninstalling and installing cmake through the SDK manager.

**Comment by x43n** [comment]
Are you using react-native-notifications ? Ensure you have followed https://wix.github.io/react-native-notifications/docs/installation-android if so.

**Comment by omnaladkar** [comment]
> build system to cmake 3.22.1

How to do this

**Comment by vaibhavw12** [comment]
ask your manager rahul

**Comment by mrousavy** [comment]
Hey - I think this has been fixed in V3 beta.

**Comment by oliverloops** [comment]
To compliment, if you're still on v2.x and having the Android issue, just clean the gradle caches with the command `./gradlew clean` on your Android native directory, then rebuild, and in case you're in Expo SDK 50 or 51, don't forget to run under a development build using `npx expo run:android`. This is more of a building issue, so I hope this works for someone using an older version.

Marc already fixed this on v3 but be aware that requires the new architecture enabled.

**Comment by ashtar23** [comment]
Hey, I'm having the same issue even after upgrading the the latest v3 beta when I enable the new architecture. My project's using expo SDK 51 an RN 0.74.3. The only time my app builds on android is when I downgrade to v2 and disable fabric. 

Any updates/ideas on this? Maybe @oliverloops would have an idea, I'd really appreciate anything at this point

**Comment by SyedZaidi714** [comment]
I am facing this issue. Can someone provide a solution for windows?

**Comment by rizwanahme06** [comment]
i am facing same issue what @phungrs is facing and i have try by cleaning and rebuilding gradlew but still it is nt working and i have also decrease the build version still facing same problem need to ask the developer of the library regarding this ,
Thank You
