### ISSUE TITLE
Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by SitaMelark** [mrousavy/react-native-mmkv#581]
After doing the installation (npm install react-native-mmkv) im getting an error when i try to initialize the storage.

```javascript
import { MMKV }from 'react-native-mmkv'; 

const storage = new MMKV(); 
``` 

This is the issue im getting:

Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you rebuilt the app., js engine: hermes

Already tried to uninstall and install, tried to unlink and link but im getting an error and also did the ./gradlew clean inside android folder but nothing worked, still getting the error.

**Comment by mrousavy** [comment]
Share your adb logcat logs.

**Comment by SitaMelark** [comment]
`
09-15 07:22:04.869  5472  5706 E ReactNativeJS: Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
09-15 07:22:04.869  5472  5706 E ReactNativeJS: * Make sure react-native-mmkv is correctly autolinked (run 'npx react-native config' to verify)
09-15 07:22:04.869  5472  5706 E ReactNativeJS: * Make sure gradle is synced.
09-15 07:22:04.869  5472  5706 E ReactNativeJS: * Make sure you rebuilt the app., js engine: hermes  
09-15 07:22:04.917  5472  5706 I ReactNativeJS: Running "Gestorum" with {"rootTag":101}
09-15 07:22:04.918  5472  5706 E ReactNativeJS: Invariant Violation: "Gestorum" has not been registered. This can happen if:
09-15 07:22:04.918  5472  5706 E ReactNativeJS: * Metro (the local dev server) is run from the wrong 
folder. Check if Metro is running, stop it and restart it in the current project.
09-15 07:22:04.918  5472  5706 E ReactNativeJS: * A module failed to load due to an error and 'AppRegistry.registerComponent' wasn't called., js engine: hermes
`
Is this what you asked for?

**Comment by mrousavy** [comment]
No, run `adb logcat` in your terminal. those are the native logs

**Comment by SitaMelark** [comment]
Started working idk why, now i can initialize it correctly. No idea what was the problem but at least is solved! Thank you anyways :)

**Comment by blackMastery** [comment]
can i get some help with this issue. 
`
Android Bundling complete 65ms
 ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure gradle is synced.
* Make sure you ran `expo prebuild`.
* Make sure you rebuilt the app., js engine: hermes
`

**Comment by wahmadx13** [comment]
@blackMastery I have the same problem did you solve the issue?

**Comment by Hassan-Mahadjir** [comment]
Did you manage to solve it? 
I am still have the same issue and I have tried most of the things I found online

**Comment by XEmAX32** [comment]
+1

**Comment by Juanma300102** [comment]
+1

**Comment by rafaelrq** [comment]
+1

**Comment by huuphat1908** [comment]
+1
