### ISSUE TITLE
Error: Failed to create a new MMKV instance:  RN76

### ISSUE THREAD

**Issue by mrzeroone0101** [mrousavy/react-native-mmkv#776]
#### Description

When using `react-native-mmkv` in my React Native project, the app fails to create a new MMKV instance and throws the following error:

```
(NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced.

[Component Stack]
```

#### Steps to Reproduce

1. Set up a React Native project (version `0.76`).
2. Install `react-native-mmkv` using `npm install react-native-mmkv`.
3. Run the app on an Android emulator or device.
4. Observe the error in logs.

#### System Information

- **OS**: Linux (Ubuntu-based)
- **React Native**: 0.76
- **Android Studio**: Latest stable release
- **MMKV Version**: Latest from npm

#### Steps Taken to Resolve

1. Verified autolinking with `npx react-native config`.
2. Enabled new architecture (TurboModules) as per [documentation](https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md).
3. Rebuilt the app and ensured Gradle sync completed.

#### Logcat Output

```
[Pixel-8-API-35-Android-15_2024-12-08_103952.zip](https://github.com/user-attachments/files/18051114/Pixel-8-API-35-Android-15_2024-12-08_103952.zip)

```

#### Expected Behavior

The MMKV instance should initialize without errors.

#### Actual Behavior

The app crashes or fails to initialize MMKV with the mentioned error.

#### Additional Information

- Let me know if more details or tests are required.

Thank you for your support! @mrousavy

**Comment by mrousavy** [comment]
there is no logcat output herey

**Comment by mrzeroone0101** [comment]
Hey @mrousavy , ```https://github.com/user-attachments/files/18051114/Pixel-8-API-35-Android-15_2024-12-08_103952.zip```
this link is a logcat file

**Comment by ariel-bentu** [comment]
+1
I get exactly this problem. MacOS laptop, with latest AndroidStudio, react native fresh app 76.4, latest MMKV. works on iOS not working on Android with the same error.

**Comment by KSayed91** [comment]
same problem here while I use

```
    "react-native": "0.76.4",
    "react-native-mmkv": "^3.1.0",
```

**Comment by shovel-kun** [comment]
Seems like RN 0.76.4 is the cause, similar linking errors happening in other libraries.

e.g latest comments in:
https://github.com/software-mansion/react-native-gesture-handler/issues/3030

**Comment by shovel-kun** [comment]
Seems like the React Native Team have fixed the issue and are working to merge the revert in the linked PR:

https://github.com/facebook/react-native/issues/48173#issuecomment-2527623384

**Comment by itsramiel** [comment]
This also happens on iOS:

```
 (NOBRIDGE) ERROR  Invariant Violation: "LocalStorage" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

rn version: 0.76.3
react-native-mmkv: 2.12.2
old arch

[Repo](https://github.com/itsramiel/MMKVError)

I see this issue is mainly concerned with Android. Do I create a seperate issue for this since it is for iOS?

**Comment by amutsch** [comment]
@mrousavy 0.76.5 is out and should resolve this issue.  Should be good to close

**Comment by amutsch** [comment]
> This also happens on iOS:
> 
> ```
>  (NOBRIDGE) ERROR  Invariant Violation: "LocalStorage" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
> ```
> 
> rn version: 0.76.3 react-native-mmkv: 2.12.2 old arch
> 
> [Repo](https://github.com/itsramiel/MMKVError)
> 
> I see this issue is mainly concerned with Android. Do I create a seperate issue for this since it is for iOS?

@itsramiel typically you would want to setup your own ticket when it isn't the same issue.  In this case you mention the project is old Arch.  76 enabled new architecture by default and I reviewed the project and it is on new arch.  You would need latest 3.x

**Comment by itsramiel** [comment]
@amutsch yes already taken care of in #779

**Comment by mrousavy** [comment]
Great, closing then

**Comment by sebbalex** [comment]
Hello,
I'm running an expo fresh installation (v52.0.18) using newest RN 0.76.5 but I still facing the issue

```
 (NOBRIDGE) ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you enabled the new architecture (TurboModules) and CodeGen properly generated the react-native-mmkv specs. See https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
* Make sure you are using react-native 0.74.0 or higher, because react-native-mmkv is a C++ TurboModule.
* Make sure you rebuilt the app.
* Make sure gradle is synced. [Component Stack]
```
anyone had a chance to test it? tnx

**Comment by uguraktas** [comment]
I have same issue 

  "expo": "~52.0.18",
  "react-native": "0.76.5",

**Comment by MOHAMED-LAAGUILI** [comment]
Downgrade to react-native-mmkv 2.x.x if you want to stay on the old architecture.
* Enable the new architecture in your app to use react-native-mmkv 3.x.x.
